fix: result directory

diff --git a/.github/workflows/make-result.yml b/.github/workflows/make-result.yml
--- a/.github/workflows/make-result.yml
+++ b/.github/workflows/make-result.yml
@@ -29,25 +29,25 @@ jobs:
       - name: clean md
         run: |
           for folder in $(find . -maxdepth 1 -type d -name "[0-9][0-9][0-9][0-9]"); do
-            rm -rf "result"
-            touch "result/$folder.md"
+            rm -r "$folder/result.md"
+            touch "$folder/result.md"
           done
       
       - name: Find and run tests for all .c files and output results in MD by directory
         run: |
           find . -type f -name '*.c' | sort | while read file; do
             folder=$(basename "$(dirname "$file")")
-            echo "# $(basename "$file")" >> "result/$folder.md"
-            # echo '```' >> "result/$folder.md"
-            bash run_tests.sh "$file" >> "result/$folder.md" || echo "Error running tests for $file" >> "result/$folder.md"
-            # echo '```' >> "result/$folder.md"
-            echo "" >> "result/$folder.md"
+            echo "# $(basename "$file")" >> "$folder/result.md"
+            # echo '```' >> "$folder/result.md"
+            bash run_tests.sh "$file" >> "$folder/result.md" || echo "Error running tests for $file" >> "$folder/result.md"
+            # echo '```' >> "$folder/result.md"
+            echo "" >> "$folder/result.md"
           done
       
       - name: Generate PDF from md
         run: |
           for folder in $(find . -maxdepth 1 -type d -name "[0-9][0-9][0-9][0-9]"); do
-            pandoc "result/$folder.md" -o "result/$folder.pdf"
+            pandoc "$folder/result.md" -o "result/$folder.pdf"
           done
 
       - name: Commit generated md files
