fix: continue running

diff --git a/.github/workflows/make-result.yml b/.github/workflows/make-result.yml
--- a/.github/workflows/make-result.yml
+++ b/.github/workflows/make-result.yml
@@ -31,7 +31,7 @@ jobs:
             folder=$(basename "$(dirname "$file")")
             echo "# $(basename "$file")" >> "$folder/result.md"
             echo '```' >> "$folder/result.md"
-            bash run_tests.sh "$file" >> "$folder/result.md"
+            bash run_tests.sh "$file" >> "$folder/result.md" || echo "Error running tests for $file" >> "$folder/result.md"
             echo '```' >> "$folder/result.md"
             echo "" >> "$folder/result.md"
           done
